apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-silo-prod
  namespace: wp-production
  labels:
    name: pv-nfs
    release: prod
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: dmz-silo.dmz.tak-cslab.org
    path: /var/nfs/wp-production

