apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-silo
  namespace: wp-staging
spec:
  accessModes:
  - ReadWriteMany
  ## PVをラベルでマッチさせるため、Nullを設定
  storageClassName: ""
  resources:
    requests:
      storage: "5Gi"
  selector:
    matchLabels:
      name: pv-nfs

